apiVersion: v1
kind: Service
metadata:
  name: postgres-service-ext
  namespace: default
spec:
  type: LoadBalancer
  ports:
    - targetPort: tcp-postgresql
      port: 5433
      protocol: TCP
  selector:
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/instance: netbox
